[project]
name = "parameter-golf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=1.26.0",
    "pandas>=3.0.2",
    "sentencepiece>=0.2.0",
    "torch==2.5.1",
    "wandb>=0.26.0",
]

[tool.uv]
torch-backend = "cu126"
